import sys
from pathlib import Path
from typing import List

# Add parent directory to path to import tools
sys.path.append(str(Path(__file__).parent.parent))

from pydantic import BaseModel, Field

# For pretty printing
from rich.console import Console
from rich.markdown import Markdown
from rich.syntax import Syntax

from tools import get_openai_llm


class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""

    code: str = Field(description="The generated code snippet to solve user's request.")
    explanation: str = Field(description="A brief explanation of how the code works.")


class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""

    has_errors: bool = Field(
        description="Does the code have any potential bugs or logical errors."
    )
    is_efficient: bool = Field(
        description="Is the code written in an efficient and optimal way."
    )
    suggested_improvement: List[str] = Field(
        description="Specific, actionable suggestions for improving the code."
    )
    critique_summary: str = Field(
        description="A concise summary of the overall critique."
    )


class RevisedCode(BaseModel):
    """Schema for the revised code after applying self-critique."""

    revised_code: str = Field(description="The final, improved Python code.")
    revision_explanation: str = Field(
        description="A summary of the changes made based on the critique."
    )


print("Pydantic models for Draft, Critique, and RefinedCode have been defined.")

llm = get_openai_llm()

# Initialize console for pretty printing
console = Console()

print("OpenAI LLM and Console are initialized.")
